apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-conversion
spec:
  selector:
    app: currency-conversion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8100
  type: LoadBalancer